// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWANUdmoH0x5TVpjENOssjpt7SbREb-M8',
    appId: '1:814176253075:web:b528a32fb174a4644b4966',
    messagingSenderId: '814176253075',
    projectId: 'safezones-636e9',
    authDomain: 'safezones-636e9.firebaseapp.com',
    storageBucket: 'safezones-636e9.appspot.com',
    measurementId: 'G-NM1REDH44M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5Avf_tOH1WXZZ8YO1U6vmc7fdwtGcax4',
    appId: '1:814176253075:android:3137bcfdb5e802e44b4966',
    messagingSenderId: '814176253075',
    projectId: 'safezones-636e9',
    storageBucket: 'safezones-636e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK5wyOWUyQs5LeSTMEwjQkmxr9rcQ7EWE',
    appId: '1:814176253075:ios:fc9cbb7897aa3b204b4966',
    messagingSenderId: '814176253075',
    projectId: 'safezones-636e9',
    storageBucket: 'safezones-636e9.appspot.com',
    iosBundleId: 'com.example.projectMds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK5wyOWUyQs5LeSTMEwjQkmxr9rcQ7EWE',
    appId: '1:814176253075:ios:1605dbfe7f45c1784b4966',
    messagingSenderId: '814176253075',
    projectId: 'safezones-636e9',
    storageBucket: 'safezones-636e9.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWANUdmoH0x5TVpjENOssjpt7SbREb-M8',
    appId: '1:814176253075:web:73c904f9c6eb3b264b4966',
    messagingSenderId: '814176253075',
    projectId: 'safezones-636e9',
    authDomain: 'safezones-636e9.firebaseapp.com',
    storageBucket: 'safezones-636e9.appspot.com',
    measurementId: 'G-YP7PRCFR57',
  );
}
